// Action types
const UPDATE_JOB_PROFILE = "UPDATE_JOB_PROFILE";
const UPDATE_LOCATION = "UPDATE_LOCATION";
const SEARCH_JOBS_REQUEST = "SEARCH_JOBS_REQUEST";
const SEARCH_JOBS_SUCCESS = "SEARCH_JOBS_SUCCESS";
const SEARCH_JOBS_FAILURE = "SEARCH_JOBS_FAILURE";

export {
  UPDATE_JOB_PROFILE,
  UPDATE_LOCATION,
  SEARCH_JOBS_REQUEST,
  SEARCH_JOBS_SUCCESS,
  SEARCH_JOBS_FAILURE,
};
